version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.33.2-alpine
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"   # Web 界面（HTTP）
      - "9443:9443"   # Web 界面（HTTPS）
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    # 宿主机 Docker 控制权限
      - portainer_data:/data                        # 数据持久化存储

volumes:
  portainer_data:
